import type { APIDefinition, ParameterDefinition } from "@apicraft/core";

export interface Generator {
  generate(): string | object;
  generateToFile?(outputPath: string): Promise<void>;
}

function capitalize(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

function camelCase(str: string): string {
  return str.replace(/[-_]([a-z])/g, (_, c) => c.toUpperCase());
}

function methodName(apiName: string, route: { method: string; path: string; handlerName: string }): string {
  const verb = route.method.toLowerCase();
  const parts = route.path.split("/").filter((p) => !p.startsWith(":"));
  const resource = parts.map((p) => capitalize(camelCase(p))).join("");
  const action = route.handlerName
    ? capitalize(route.handlerName)
    : resource || capitalize(verb);
  return `${verb}${action}`;
}

function tsTypeFromSchema(type: { kind: string; name?: string; enum?: string[]; properties?: Record<string, unknown>; required?: string[]; items?: unknown; members?: unknown[] }): string {
  switch (type.kind) {
    case "string":
      return "string";
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "array":
      return "unknown[]";
    case "object":
    case "reference":
      return type.name || "unknown";
    case "enum":
      return type.name || "string";
    default:
      return "unknown";
  }
}

function needsRequestBody(method: string): boolean {
  return method === "post" || method === "put" || method === "patch";
}

function isPaginated(params: ParameterDefinition[]): boolean {
  const names = params.map((p) => p.name.toLowerCase());
  return names.includes("page") && (names.includes("limit") || names.includes("per_page") || names.includes("perPage"));
}

export class ReactQueryGenerator implements Generator {
  constructor(private definitions: APIDefinition[]) {}

  generate(): string {
    const lines: string[] = [];

    lines.push("// Auto-generated by @apicraft/generator-react");
    lines.push("// Do not edit this file directly");
    lines.push("");
    lines.push('import {');
    lines.push('  useQuery,');
    lines.push('  useMutation,');
    lines.push('  useInfiniteQuery,');
    lines.push('  useQueryClient,');
    lines.push('  type UseQueryResult,');
    lines.push('  type UseMutationResult,');
    lines.push('  type UseInfiniteQueryResult,');
    lines.push('  type QueryKey,');
    lines.push("} from '@tanstack/react-query';");
    lines.push("");

    lines.push("// ── Import Client ──");
    lines.push("import { APICraftClient } from '@apicraft/generator-client';");
    lines.push("");

    lines.push("let client: APICraftClient;");
    lines.push("");
    lines.push("export function setApiClient(apiClient: APICraftClient): void {");
    lines.push("  client = apiClient;");
    lines.push("}");
    lines.push("");

    for (const api of this.definitions) {
      for (const route of api.routes) {
        this.generateHook(lines, api, route);
        lines.push("");
      }
    }

    return lines.join("\n");
  }

  generateToFile(outputPath: string): Promise<void> {
    const content = this.generate();
    return Promise.resolve().then(() => {
      const fs = require("fs");
      fs.writeFileSync(outputPath, content, "utf-8");
    });
  }

  private generateHook(lines: string[], api: APIDefinition, route: { method: string; path: string; fullPath: string; handlerName: string; parameters: ParameterDefinition[]; summary?: string; description?: string }): void {
    const mName = methodName(api.name, route);
    const hookName = `use${capitalize(mName)}`;
    const isGet = route.method === "get";
    const isPaginatedRoute = isPaginated(route.parameters);
    const hasBody = route.parameters.some((p) => p.kind === "body");
    const queryParams = route.parameters.filter((p) => p.kind === "query");

    const responseType = this.inferResponseType(route);

    lines.push("  /**");
    if (route.summary) lines.push(`   * ${route.summary}`);
    if (route.description) lines.push(`   * ${route.description}`);
    lines.push(`   * ${route.method.toUpperCase()} ${route.fullPath || `${api.prefix}${route.path}`}`);
    lines.push("   */");

    if (isGet) {
      if (isPaginatedRoute) {
        this.generateInfiniteQueryHook(lines, hookName, mName, api, route, queryParams, responseType);
      } else {
        this.generateQueryHook(lines, hookName, mName, api, route, queryParams, responseType);
      }
    } else {
      this.generateMutationHook(lines, hookName, mName, api, route, hasBody, responseType);
    }
  }

  private generateQueryHook(
    lines: string[],
    hookName: string,
    mName: string,
    api: APIDefinition,
    route: { method: string; path: string; handlerName: string; parameters: ParameterDefinition[] },
    queryParams: ParameterDefinition[],
    responseType: string,
  ): void {
    const paramType = queryParams.length > 0
      ? `params${queryParams.every((p) => !p.required) ? "?" : ""}: { ${queryParams.map((p) => `${p.name}${p.required ? "" : "?"}: ${tsTypeFromSchema(p.type)}`).join("; ")} }`
      : "";
    const resourceKey = this.resourceKey(api);
    const clientMethod = route.handlerName || mName;

    lines.push(`export function ${hookName}(${paramType}): UseQueryResult<${responseType}> {`);
    lines.push("  return useQuery({");
    lines.push(`    queryKey: ['${resourceKey}', '${route.handlerName}', params],`);
    lines.push(`    queryFn: () => client.${clientMethod}(params),`);
    lines.push("  });");
    lines.push("}");
  }

  private generateInfiniteQueryHook(
    lines: string[],
    hookName: string,
    mName: string,
    api: APIDefinition,
    route: { method: string; path: string; handlerName: string; parameters: ParameterDefinition[] },
    queryParams: ParameterDefinition[],
    responseType: string,
  ): void {
    const paramType = queryParams.length > 0
      ? `initialParams?: { ${queryParams.map((p) => `${p.name}${p.required ? "" : "?"}: ${tsTypeFromSchema(p.type)}`).join("; ")} }`
      : "";
    const resourceKey = this.resourceKey(api);
    const clientMethod = route.handlerName || mName;

    lines.push(`export function ${hookName}(${paramType}): UseInfiniteQueryResult<${responseType}> {`);
    lines.push("  return useInfiniteQuery({");
    lines.push(`    queryKey: ['${resourceKey}', '${route.handlerName}'],`);
    lines.push("    queryFn: ({ pageParam = 1 }) =>");
    lines.push(`      client.${clientMethod}({ ...initialParams, page: pageParam as number }),`);
    lines.push("    getNextPageParam: (lastPage, allPages) => {");
    lines.push("      const totalPages = (lastPage as any)?.totalPages ?? 1;");
    lines.push("      const nextPage = allPages.length + 1;");
    lines.push("      return nextPage <= totalPages ? nextPage : undefined;");
    lines.push("    },");
    lines.push("    initialPageParam: 1,");
    lines.push("  });");
    lines.push("}");
  }

  private generateMutationHook(
    lines: string[],
    hookName: string,
    mName: string,
    api: APIDefinition,
    route: { method: string; path: string; fullPath: string; handlerName: string; parameters: ParameterDefinition[] },
    hasBody: boolean,
    responseType: string,
  ): void {
    const bodyParam = route.parameters.find((p) => p.kind === "body");
    const bodyType = bodyParam ? tsTypeFromSchema(bodyParam.type) : "void";
    const resourceKey = this.resourceKey(api);
    const clientMethod = route.handlerName || mName;

    lines.push(`export function ${hookName}(): UseMutationResult<${responseType}, Error, ${hasBody ? bodyType : "void"}> {`);
    lines.push("  const queryClient = useQueryClient();");
    lines.push("  return useMutation({");
    lines.push(`    mutationFn: (${hasBody ? "body" : "_void"}: ${hasBody ? bodyType : "void"}) =>`);
    lines.push(`      client.${clientMethod}(${hasBody ? "body" : ""}),`);
    lines.push(`    onSuccess: () => {`);
    lines.push(`      queryClient.invalidateQueries({ queryKey: ['${resourceKey}'] });`);
    lines.push("    },");
    lines.push("  });");
    lines.push("}");
  }

  private resourceKey(api: APIDefinition): string {
    const prefix = api.prefix.replace(/^\//, "").replace(/\//g, "_");
    return prefix || api.name.toLowerCase().replace(/\s+/g, "_");
  }

  private inferResponseType(route: { parameters: ParameterDefinition[]; method: string }): string {
    const bodyParam = route.parameters.find((p) => p.kind === "body");
    if (bodyParam && (bodyParam.type.kind === "object" || bodyParam.type.kind === "reference")) {
      return bodyParam.type.name || "unknown";
    }
    return "unknown";
  }
}

export default ReactQueryGenerator;
