// Auto-generated by APICraft — do not edit.
// Handles GET /api/posts and POST /api/posts
import { NextRequest, NextResponse } from "next/server"
import { executeRequest } from "@apicraft/adapter-next"

export async function GET(request: NextRequest): Promise<NextResponse> {
  const result = await executeRequest("GET", "/api/posts", request, {})
  if (result.status >= 400 && typeof result.body === "object" && result.body !== null) {
    return NextResponse.json(result.body, {
      status: result.status,
      headers: result.headers as Record<string, string>,
    })
  }
  if (result.body !== null && result.body !== undefined) {
    return NextResponse.json(result.body, {
      status: result.status,
      headers: result.headers as Record<string, string>,
    })
  }
  return new NextResponse(null, { status: result.status })
}

export async function POST(request: NextRequest): Promise<NextResponse> {
  const result = await executeRequest("POST", "/api/posts", request, {})
  if (result.status >= 400 && typeof result.body === "object" && result.body !== null) {
    return NextResponse.json(result.body, {
      status: result.status,
      headers: result.headers as Record<string, string>,
    })
  }
  if (result.body !== null && result.body !== undefined) {
    return NextResponse.json(result.body, {
      status: result.status,
      headers: result.headers as Record<string, string>,
    })
  }
  return new NextResponse(null, { status: result.status })
}
