import type { APIDefinition, ParameterDefinition, TypeSchema } from "@apicraft/core";

export interface Generator {
  generate(): string | object;
  generateToFile?(outputPath: string): Promise<void>;
}

function capitalize(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

function camelCase(str: string): string {
  return str.replace(/[-_]([a-z])/g, (_, c) => c.toUpperCase());
}

function safeIdentifier(name: string): string {
  return name.replace(/[^a-zA-Z0-9_$]/g, "_");
}

function schemaVarName(prefix: string, suffix: string): string {
  return `${camelCase(prefix)}${capitalize(camelCase(suffix))}Schema`;
}

export class ZodSchemaGenerator implements Generator {
  constructor(private definitions: APIDefinition[]) {}

  generate(): string {
    const lines: string[] = [];

    lines.push("// Auto-generated by @apicraft/generator-zod");
    lines.push("// Do not edit this file directly");
    lines.push("");
    lines.push("import { z } from 'zod';");
    lines.push("");

    for (const api of this.definitions) {
      const prefix = api.name;

      for (const route of api.routes) {
        const routeName = route.handlerName || camelCase(route.path);

        const queryParams = route.parameters.filter((p) => p.kind === "query");
        const pathParams = route.parameters.filter((p) => p.kind === "param");
        const bodyParams = route.parameters.filter((p) => p.kind === "body");
        const headerParams = route.parameters.filter((p) => p.kind === "headers");

        if (queryParams.length > 0) {
          this.generateParamSchema(lines, prefix, routeName, "queryParams", queryParams);
        }

        if (pathParams.length > 0) {
          this.generateParamSchema(lines, prefix, routeName, "pathParams", pathParams);
        }

        if (bodyParams.length > 0) {
          this.generateBodySchema(lines, prefix, routeName, bodyParams[0]);
        }

        if (headerParams.length > 0) {
          this.generateParamSchema(lines, prefix, routeName, "headers", headerParams);
        }
      }

      this.generateApiResponseSchemas(lines, api);
    }

    return lines.join("\n");
  }

  generateToFile(outputPath: string): Promise<void> {
    const content = this.generate();
    return Promise.resolve().then(() => {
      const fs = require("fs");
      fs.writeFileSync(outputPath, content, "utf-8");
    });
  }

  private generateParamSchema(
    lines: string[],
    prefix: string,
    routeName: string,
    suffix: string,
    params: ParameterDefinition[],
  ): void {
    const varName = schemaVarName(`${prefix}_${routeName}`, suffix);

    lines.push(`// ${prefix}:${routeName} ${suffix}`);
    lines.push(`export const ${varName} = z.object({`);

    for (const param of params) {
      const optional = param.required ? "" : ".optional()";
      const defaultValue = param.default !== undefined ? `.default(${JSON.stringify(param.default)})` : "";
      const zodChain = this.typeToZodChain(param.type, param.zodSchema);
      lines.push(`  ${param.name}: ${zodChain}${optional}${defaultValue},`);
    }

    lines.push("});");
    lines.push("");
  }

  private generateBodySchema(
    lines: string[],
    prefix: string,
    routeName: string,
    param: ParameterDefinition,
  ): void {
    const varName = schemaVarName(`${prefix}_${routeName}`, "body");
    const typeName = param.type.name || `${capitalize(prefix)}${capitalize(routeName)}Body`;

    if (param.type.kind === "object" && param.type.properties) {
      lines.push(`// ${prefix}:${routeName} body`);
      lines.push(`export const ${varName}: z.ZodType<${typeName}> = z.object({`);

      for (const [key, propType] of Object.entries(param.type.properties)) {
        const required = param.type.required?.includes(key) ? "" : ".optional()";
        const zodChain = this.typeToZodChain(propType);
        lines.push(`  ${key}: ${zodChain}${required},`);
      }

      lines.push("});");
      lines.push("");
    } else if (param.type.kind === "reference" && param.type.name) {
      lines.push(`export const ${varName}: z.ZodType<${param.type.name}> = z.object({});`);
      lines.push("");
    }
  }

  private generateApiResponseSchemas(lines: string[], api: APIDefinition): void {
    const schemas = this.collectSchemas(api);

    for (const [name, schema] of schemas) {
      if (schema.kind === "object" && schema.properties) {
        lines.push(`// Response schema: ${name}`);
        lines.push(`export const ${safeIdentifier(name)}Schema: z.ZodType<${name}> = z.object({`);

        for (const [key, propType] of Object.entries(schema.properties)) {
          const required = schema.required?.includes(key) ? "" : ".optional()";
          const zodChain = this.typeToZodChain(propType);
          lines.push(`  ${key}: ${zodChain}${required},`);
        }

        lines.push("});");
        lines.push("");
      }
    }
  }

  private typeToZodChain(type: TypeSchema, zodSchema?: unknown): string {
    switch (type.kind) {
      case "string": {
        let chain = "z.string()";
        if (type.zodInfo?.email) chain += ".email()";
        if (type.zodInfo?.uuid) chain += ".uuid()";
        if (type.zodInfo?.pattern) chain += `.regex(${JSON.stringify(type.zodInfo.pattern)})`;
        if (type.zodInfo?.min !== undefined) chain += `.min(${type.zodInfo.min})`;
        if (type.zodInfo?.max !== undefined) chain += `.max(${type.zodInfo.max})`;
        return chain;
      }

      case "number": {
        let chain = "z.number()";
        if (type.zodInfo?.min !== undefined) chain += `.min(${type.zodInfo.min})`;
        if (type.zodInfo?.max !== undefined) chain += `.max(${type.zodInfo.max})`;
        return chain;
      }

      case "boolean": {
        return "z.boolean()";
      }

      case "array": {
        const items = type.items ? this.typeToZodChain(type.items) : "z.unknown()";
        let chain = `z.array(${items})`;
        if (type.zodInfo?.min !== undefined) chain += `.min(${type.zodInfo.min})`;
        if (type.zodInfo?.max !== undefined) chain += `.max(${type.zodInfo.max})`;
        return chain;
      }

      case "object": {
        if (type.properties && Object.keys(type.properties).length > 0) {
          const props = Object.entries(type.properties)
            .map(([key, propType]) => {
              const required = type.required?.includes(key) ? "" : ".optional()";
              return `${key}: ${this.typeToZodChain(propType)}${required}`;
            })
            .join(", ");
          return `z.object({ ${props} })`;
        }
        return "z.object({})";
      }

      case "enum": {
        if (type.enum && type.enum.length > 0) {
          const values = type.enum.map((e) => JSON.stringify(e)).join(", ");
          return `z.enum([${values}])`;
        }
        return "z.string()";
      }

      case "union": {
        if (type.members && type.members.length > 0) {
          const members = type.members.map((m) => this.typeToZodChain(m)).join(", ");
          return `z.union([${members}])`;
        }
        return "z.unknown()";
      }

      case "reference": {
        if (type.name) {
          return `${safeIdentifier(type.name)}Schema`;
        }
        return "z.unknown()";
      }

      default:
        return "z.unknown()";
    }
  }

  private collectSchemas(api: APIDefinition): Map<string, TypeSchema> {
    const schemas = new Map<string, TypeSchema>();

    for (const route of api.routes) {
      for (const param of route.parameters) {
        if (param.type.kind === "object" && param.type.name) {
          if (!schemas.has(param.type.name)) {
            schemas.set(param.type.name, param.type);
          }
        }
        if (param.type.kind === "reference" && param.type.name) {
          if (!schemas.has(param.type.name)) {
            schemas.set(param.type.name, param.type);
          }
        }
        if (param.type.kind === "array" && param.type.items && param.type.items.name) {
          if (!schemas.has(param.type.items.name)) {
            schemas.set(param.type.items.name, param.type.items);
          }
        }
      }
    }

    return schemas;
  }
}

export default ZodSchemaGenerator;
