import type { APIDefinition, ParameterDefinition, TypeSchema } from "@apicraft/core";

export interface Generator {
  generate(): string | object;
  generateToFile?(outputPath: string): Promise<void>;
}

function capitalize(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

function camelCase(str: string): string {
  return str.replace(/[-_]([a-z])/g, (_, c) => c.toUpperCase());
}

function safeIdentifier(name: string): string {
  return name.replace(/[^a-zA-Z0-9_$]/g, "_");
}

function methodName(apiName: string, route: { method: string; path: string; handlerName: string }): string {
  const parts = route.path.split("/").filter(Boolean);
  const verb = route.method.toLowerCase();
  const resource = parts
    .filter((p) => !p.startsWith(":"))
    .map((p) => capitalize(camelCase(p)))
    .join("");
  const action = route.handlerName
    ? capitalize(route.handlerName)
    : resource || capitalize(verb);
  return `${verb}${action}`;
}

function tsTypeFromSchema(type: TypeSchema): string {
  switch (type.kind) {
    case "string":
      return "string";
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "array": {
      const itemType = type.items ? tsTypeFromSchema(type.items) : "unknown";
      return `${itemType}[]`;
    }
    case "object": {
      if (type.name) return type.name;
      if (!type.properties || Object.keys(type.properties).length === 0) return "Record<string, unknown>";
      const props = Object.entries(type.properties)
        .map(([key, propType]) => {
          const optional = !type.required?.includes(key) ? "?" : "";
          return `${key}${optional}: ${tsTypeFromSchema(propType)}`;
        })
        .join("; ");
      return `{ ${props} }`;
    }
    case "enum":
      if (type.enum && type.enum.length > 0) {
        return type.enum.map((e) => `"${e}"`).join(" | ");
      }
      return "string";
    case "union":
      if (type.members && type.members.length > 0) {
        return type.members.map((m) => tsTypeFromSchema(m)).join(" | ");
      }
      return "unknown";
    case "reference":
      return type.name || "unknown";
    default:
      return "unknown";
  }
}

function extractResponseType(route: { parameters: ParameterDefinition[]; method: string }): string {
  const bodyParam = route.parameters.find((p) => p.kind === "body");
  if (bodyParam && bodyParam.type.kind === "reference") {
    return bodyParam.type.name || "unknown";
  }
  if (bodyParam && bodyParam.type.kind === "object") {
    return bodyParam.type.name || "unknown";
  }

  const isList = route.method === "get" || route.method === "delete";
  return isList ? "unknown[]" : "unknown";
}

function needsRequestBody(method: string): boolean {
  return method === "post" || method === "put" || method === "patch";
}

export class ClientSDKGenerator implements Generator {
  constructor(private definitions: APIDefinition[]) {}

  generate(): string {
    return this.generateFetchClient();
  }

  generateFetchClient(): string {
    return this.generateClient("fetch");
  }

  generateAxiosClient(): string {
    return this.generateClient("axios");
  }

  generateToFile(outputPath: string): Promise<void> {
    const content = this.generateFetchClient();
    return Promise.resolve().then(() => {
      const fs = require("fs");
      fs.writeFileSync(outputPath, content, "utf-8");
    });
  }

  private generateClient(library: "fetch" | "axios"): string {
    const lines: string[] = [];
    const responseTypes = this.collectResponseTypes();

    lines.push("// Auto-generated by @apicraft/generator-client");
    lines.push("// Do not edit this file directly");
    lines.push("");

    if (library === "axios") {
      lines.push('import axios, { AxiosInstance, AxiosRequestConfig } from "axios";');
      lines.push("");
    }

    if (responseTypes.size > 0) {
      lines.push("// ── Response Types ──");
      lines.push("");

      for (const [name, typeDef] of responseTypes) {
        lines.push(`export interface ${name} {`);
        if (typeDef.kind === "object" && typeDef.properties) {
          for (const [key, prop] of Object.entries(typeDef.properties)) {
            const optional = typeDef.required?.includes(key) ? "" : "?";
            lines.push(`  ${key}${optional}: ${tsTypeFromSchema(prop)};`);
          }
        }
        lines.push("}");
        lines.push("");
      }
    }

    lines.push("// ── Error Types ──");
    lines.push("");
    lines.push("export class APIError extends Error {");
    lines.push("  constructor(");
    lines.push("    public status: number,");
    lines.push("    public body: unknown,");
    lines.push("  ) {");
    lines.push('    super(`API Error: ${status}`);');
    lines.push("    this.name = 'APIError';");
    lines.push("  }");
    lines.push("}");
    lines.push("");

    if (library === "fetch") {
      this.generateFetchClientClass(lines);
    } else {
      this.generateAxiosClientClass(lines);
    }

    return lines.join("\n");
  }

  private generateFetchClientClass(lines: string[]): void {
    lines.push("// ── Fetch Client ──");
    lines.push("");
    lines.push("export class APICraftClient {");
    lines.push("  constructor(private baseUrl: string) {}");
    lines.push("");

    for (const api of this.definitions) {
      for (const route of api.routes) {
        this.generateFetchMethod(lines, api, route);
      }
    }

    lines.push("}");
    lines.push("");
  }

  private generateFetchMethod(lines: string[], api: APIDefinition, route: { method: string; path: string; fullPath: string; handlerName: string; parameters: ParameterDefinition[]; summary?: string; description?: string }): void {
    const mName = methodName(api.name, route);
    const hasQuery = route.parameters.some((p) => p.kind === "query");
    const hasBody = route.parameters.some((p) => p.kind === "body");
    const hasPath = route.parameters.some((p) => p.kind === "param");
    const responseType = extractResponseType(route);

    const allParams: string[] = [];
    const queryParams = route.parameters.filter((p) => p.kind === "query");
    const bodyParam = route.parameters.find((p) => p.kind === "body");

    if (queryParams.length > 0) {
      const queryType = queryParams
        .map((p) => `${p.name}${p.required ? "" : "?"}: ${tsTypeFromSchema(p.type)}`)
        .join("; ");
      allParams.push(`params?: { ${queryType} }`);
    }

    if (bodyParam && needsRequestBody(route.method)) {
      allParams.push(`body: ${tsTypeFromSchema(bodyParam.type)}`);
    }

    lines.push("  /**");
    if (route.summary) lines.push(`   * ${route.summary}`);
    if (route.description) lines.push(`   * ${route.description}`);
    lines.push(`   * ${route.method.toUpperCase()} ${route.fullPath || `${api.prefix}${route.path}`}`);
    lines.push("   */");
    lines.push(`  async ${mName}(${allParams.join(", ")}): Promise<${responseType}> {`);

    const pathTemplate = this.buildPathTemplate(route, api);
    lines.push(`    let url = \`\${this.baseUrl}${pathTemplate}\`;`);

    if (hasQuery && queryParams.length > 0) {
      lines.push("    const searchParams = new URLSearchParams();");
      for (const qp of queryParams) {
        lines.push(`    if (params?.${qp.name} !== undefined) searchParams.set('${qp.name}', String(params.${qp.name}));`);
      }
      lines.push("    const qs = searchParams.toString();");
      lines.push("    if (qs) url += `?${qs}`;");
    }

    if (needsRequestBody(route.method) && hasBody) {
      lines.push("    const res = await fetch(url, {");
      lines.push(`      method: '${route.method.toUpperCase()}',`);
      lines.push("      headers: { 'Content-Type': 'application/json' },");
      lines.push("      body: JSON.stringify(body),");
      lines.push("    });");
    } else if (route.method === "delete") {
      lines.push("    const res = await fetch(url, {");
      lines.push("      method: 'DELETE',");
      lines.push("    });");
    } else {
      lines.push("    const res = await fetch(url);");
    }

    lines.push("    if (!res.ok) {");
    lines.push("      const errorBody = await res.json().catch(() => ({ message: res.statusText }));");
    lines.push("      throw new APIError(res.status, errorBody);");
    lines.push("    }");
    lines.push("    return res.json();");
    lines.push("  }");
    lines.push("");
  }

  private generateAxiosClientClass(lines: string[]): void {
    lines.push("// ── Axios Client ──");
    lines.push("");
    lines.push("export class APICraftAxiosClient {");
    lines.push("  constructor(private client: AxiosInstance) {}");
    lines.push("");

    for (const api of this.definitions) {
      for (const route of api.routes) {
        this.generateAxiosMethod(lines, api, route);
      }
    }

    lines.push("}");
    lines.push("");
  }

  private generateAxiosMethod(lines: string[], api: APIDefinition, route: { method: string; path: string; fullPath: string; handlerName: string; parameters: ParameterDefinition[]; summary?: string; description?: string }): void {
    const mName = methodName(api.name, route);
    const hasQuery = route.parameters.some((p) => p.kind === "query");
    const hasBody = route.parameters.some((p) => p.kind === "body");
    const hasPath = route.parameters.some((p) => p.kind === "param");
    const responseType = extractResponseType(route);

    const allParams: string[] = [];
    const queryParams = route.parameters.filter((p) => p.kind === "query");
    const bodyParam = route.parameters.find((p) => p.kind === "body");

    if (queryParams.length > 0) {
      const queryType = queryParams
        .map((p) => `${p.name}${p.required ? "" : "?"}: ${tsTypeFromSchema(p.type)}`)
        .join("; ");
      allParams.push(`params?: { ${queryType} }`);
    }

    if (bodyParam && needsRequestBody(route.method)) {
      allParams.push(`body: ${tsTypeFromSchema(bodyParam.type)}`);
    }

    lines.push("  /**");
    if (route.summary) lines.push(`   * ${route.summary}`);
    if (route.description) lines.push(`   * ${route.description}`);
    lines.push(`   * ${route.method.toUpperCase()} ${route.fullPath || `${api.prefix}${route.path}`}`);
    lines.push("   */");
    lines.push(`  async ${mName}(${allParams.join(", ")}): Promise<${responseType}> {`);

    const pathTemplate = this.buildPathTemplate(route, api);
    lines.push("    const config: AxiosRequestConfig = {};");

    if (hasQuery && queryParams.length > 0) {
      lines.push("    config.params = params;");
    }

    lines.push(`    const url = \`${pathTemplate}\`;`);

    if (needsRequestBody(route.method) && hasBody) {
      lines.push(`    const res = await this.client.${route.method}<${responseType}>(url, body, config);`);
    } else {
      lines.push(`    const res = await this.client.${route.method}<${responseType}>(url, config);`);
    }

    lines.push("    return res.data;");
    lines.push("  }");
    lines.push("");
  }

  private buildPathTemplate(route: { path: string; fullPath: string; parameters: ParameterDefinition[] }, api: APIDefinition): string {
    const fullPath = route.fullPath || `${api.prefix}${route.path}`;
    let template = fullPath.replace(/:([a-zA-Z_][a-zA-Z0-9_]*)/g, "${$1}");

    const pathParams = route.parameters.filter((p) => p.kind === "param");
    for (const pp of pathParams) {
      if (template.includes(`\${${pp.name}}`)) continue;
      if (fullPath.includes(`:${pp.name}`)) continue;
    }

    return template;
  }

  private collectResponseTypes(): Map<string, TypeSchema> {
    const types = new Map<string, TypeSchema>();

    for (const api of this.definitions) {
      for (const route of api.routes) {
        for (const param of route.parameters) {
          if ((param.type.kind === "object" || param.type.kind === "reference") && param.type.name) {
            if (!types.has(param.type.name)) {
              types.set(param.type.name, param.type);
            }
          }

          if (param.type.kind === "array" && param.type.items) {
            if ((param.type.items.kind === "object" || param.type.items.kind === "reference") && param.type.items.name) {
              if (!types.has(param.type.items.name)) {
                types.set(param.type.items.name, param.type.items);
              }
            }
          }
        }
      }
    }

    return types;
  }
}

export default ClientSDKGenerator;
