// Auto-generated by APICraft — do not edit.
// Handles GET /api/posts/:id, PATCH /api/posts/:id, DELETE /api/posts/:id
import { NextRequest, NextResponse } from "next/server"
import { executeRequest } from "@apicraft/adapter-next"

export async function GET(
  request: NextRequest,
  { params }: { params: Record<string, string> },
): Promise<NextResponse> {
  const result = await executeRequest("GET", "/api/posts/:id", request, params)
  if (result.status >= 400 && typeof result.body === "object" && result.body !== null) {
    return NextResponse.json(result.body, {
      status: result.status,
      headers: result.headers as Record<string, string>,
    })
  }
  if (result.body !== null && result.body !== undefined) {
    return NextResponse.json(result.body, {
      status: result.status,
      headers: result.headers as Record<string, string>,
    })
  }
  return new NextResponse(null, { status: result.status })
}

export async function PATCH(
  request: NextRequest,
  { params }: { params: Record<string, string> },
): Promise<NextResponse> {
  const result = await executeRequest("PATCH", "/api/posts/:id", request, params)
  if (result.status >= 400 && typeof result.body === "object" && result.body !== null) {
    return NextResponse.json(result.body, {
      status: result.status,
      headers: result.headers as Record<string, string>,
    })
  }
  if (result.body !== null && result.body !== undefined) {
    return NextResponse.json(result.body, {
      status: result.status,
      headers: result.headers as Record<string, string>,
    })
  }
  return new NextResponse(null, { status: result.status })
}

export async function DELETE(
  request: NextRequest,
  { params }: { params: Record<string, string> },
): Promise<NextResponse> {
  const result = await executeRequest("DELETE", "/api/posts/:id", request, params)
  if (result.status >= 400 && typeof result.body === "object" && result.body !== null) {
    return NextResponse.json(result.body, {
      status: result.status,
      headers: result.headers as Record<string, string>,
    })
  }
  if (result.body !== null && result.body !== undefined) {
    return NextResponse.json(result.body, {
      status: result.status,
      headers: result.headers as Record<string, string>,
    })
  }
  return new NextResponse(null, { status: result.status })
}
